package in.sweetcherry.pswebservice.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;



@Entity
@Table(name="ps_address")
public class Address {
	
	// ------------------------
		// PRIVATE FIELDS
		// ------------------------
		  
		// An autogenerated id (unique for each user in the db)
		@Id
		@GeneratedValue(strategy = GenerationType.AUTO)
		@Column(name="id_address")
		private long addressId;
		
		@Column(name="company")
		private String company;
		
		@Column(name="firstname")
		private String firstName;
		
		@Column(name="lastname")
		private String lastName;
		
		@Column(name="address1")
		private String address1;
		
		@Column(name="address2")
		private String address2;
		
		@Column(name="postcode")
		private String postalCode;
		
		@Column(name="city")
		private String city;
		
		@Column(name="phone")
		private String phone;
		
		@Column(name="phone_mobile")
		private String mobilePhone;
		
		//-----------------------------------
		// PUBLIC METHODS
		//-----------------------------------
		
		public Address() {
			super();
			// TODO Auto-generated constructor stub
		}

		public Address(long addressId, String company, String firstName, String lastName, String address1,
				String address2, String postalCode, String city, String phone, String mobilePhone) {
			super();
			this.addressId = addressId;
			this.company = company;
			this.firstName = firstName;
			this.lastName = lastName;
			this.address1 = address1;
			this.address2 = address2;
			this.postalCode = postalCode;
			this.city = city;
			this.phone = phone;
			this.mobilePhone = mobilePhone;
		}

		public long getAddressId() {
			return addressId;
		}

		public void setAddressId(long addressId) {
			this.addressId = addressId;
		}

		public String getCompany() {
			return company;
		}

		public void setCompany(String company) {
			this.company = company;
		}

		public String getFirstName() {
			return firstName;
		}

		public void setFirstName(String firstName) {
			this.firstName = firstName;
		}

		public String getLastName() {
			return lastName;
		}

		public void setLastName(String lastName) {
			this.lastName = lastName;
		}

		public String getAddress1() {
			return address1;
		}

		public void setAddress1(String address1) {
			this.address1 = address1;
		}

		public String getAddress2() {
			return address2;
		}

		public void setAddress2(String address2) {
			this.address2 = address2;
		}

		public String getPostalCode() {
			return postalCode;
		}

		public void setPostalCode(String postalCode) {
			this.postalCode = postalCode;
		}

		public String getCity() {
			return city;
		}

		public void setCity(String city) {
			this.city = city;
		}

		public String getPhone() {
			return phone;
		}

		public void setPhone(String phone) {
			this.phone = phone;
		}

		public String getMobilePhone() {
			return mobilePhone;
		}

		public void setMobilePhone(String mobilePhone) {
			this.mobilePhone = mobilePhone;
		}

		


}
