package in.sweetcherry.pswebservice.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

/**
 * An entity Employee composed by fields (id_employee, email, firstname, lastname, passwd, id_profile).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author Amit Malagi
 */
@Entity
@Table(name = "ps_employee")
public class Employee {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------
	  
	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="id_employee")
	private long employeeId;
	  
	// The user's email
	@NotNull
	private String email;
	  
	// The user's name
	@NotNull
	private String firstname;
	
	@NotNull
	private String lastname;
	
	@NotNull
	private String passwd;
	
	@NotNull
	@Column(name="id_lang")
	private long langId;
	
	@NotNull
	@Column(name="id_profile")
	private long profileId;
	
	@NotNull
	@Column(name="active")
	private int status;

	@Transient
	private String profile;
	
	/*@Transient
	private String token;*/
	
	// ------------------------
	// PUBLIC METHODS
	// ------------------------
	
	public Employee() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	public Employee(long employeeId) {
		this.employeeId = employeeId;
	}
	
	public Employee(String email, String firstname, String lastname,  String passwd, long langId, long profileId, int status) {
		this.email = email;
		this.firstname = firstname;
		this.lastname = lastname;
		this.passwd = passwd;
		this.langId = langId;
		this.profileId = profileId;
		this.status = status;
	}

	public long getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(long employeeId) {
		this.employeeId = employeeId;
	}

	public long getLangId() {
		return langId;
	}

	public void setLangId(long langId) {
		this.langId = langId;
	}

	public long getProfileId() {
		return profileId;
	}

	public void setProfileId(long profileId) {
		this.profileId = profileId;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getPasswd() {
		return passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	
	public String getProfile() {
		return profile;
	}

	public void setProfile(String profile) {
		this.profile = profile;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}
	
	/*public void setToken(String token) {
		this.token = token;
	}
	
	public String getToken() {
		return token;
	}*/
		
}
