package in.sweetcherry.pswebservice.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;



@Entity
@Table(name="ps_order_detail")
public class OrderDetail {
	
	// ------------------------
		// PRIVATE FIELDS
		// ------------------------
		  
		// An autogenerated id (unique for each user in the db)
		@Id
		@GeneratedValue(strategy = GenerationType.AUTO)
		@Column(name="id_order_detail")
		private long orderDetailId;
		
		@Column(name="id_order")
		private long orderId;
		
		@NotNull
		@Column(name="product_name")
		private String productName;
		
		//@NotNull
		@Column(name="product_quantity")
		private long productQuantity;
		
		
		
		//-----------------------------------
		// PUBLIC METHODS
		//-----------------------------------
		
		public OrderDetail() {
			super();
			// TODO Auto-generated constructor stub
		}



		public OrderDetail(long orderDetailId, long orderId, String productName, long productQuantity) {
			super();
			this.orderDetailId = orderDetailId;
			this.orderId = orderId;
			this.productName = productName;
			this.productQuantity = productQuantity;
		}



		public long getOrderDetailId() {
			return orderDetailId;
		}



		public void setOrderDetailId(long orderDetailId) {
			this.orderDetailId = orderDetailId;
		}



		public long getOrderId() {
			return orderId;
		}



		public void setOrderId(long orderId) {
			this.orderId = orderId;
		}



		public String getProductName() {
			return productName;
		}



		public void setProductName(String productName) {
			this.productName = productName;
		}



		public long getProductQuantity() {
			return productQuantity;
		}



		public void setProductQuantity(long productQuantity) {
			this.productQuantity = productQuantity;
		}

		
		
		
		
		
		
		
		
		
		

}
