package in.sweetcherry.pswebservice.models;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;



@Entity
@Table(name="ps_order_history")
public class OrderHistory {
	
	// ------------------------
		// PRIVATE FIELDS
		// ------------------------
		  
		// An autogenerated id (unique for each user in the db)
		@Id
		@GeneratedValue(strategy = GenerationType.AUTO)
		@Column(name="id_order_history")
		private long orderHistoryId;
		
		@Column(name="id_employee")
		private long employeeId;
		
		@Column(name="id_order")
		private long orderId;
		
		@Column(name="id_order_state")
		private long orderStateId;
		
		@Column(name="date_add")
		//@Temporal(TemporalType.TIMESTAMP)
		private String addedDate;
		
		//-----------------------------------
		// PUBLIC METHODS
		//-----------------------------------
		
		public OrderHistory() {
			super();
			// TODO Auto-generated constructor stub
		}

		public OrderHistory(long employeeId, long orderId, long orderStateId, String addedDate) {
			super();
			this.employeeId = employeeId;
			this.orderId = orderId;
			this.orderStateId = orderStateId;
			this.addedDate = addedDate;
		}

		public long getOrderHistoryId() {
			return orderHistoryId;
		}

		public void setOrderHistoryId(long orderHistoryId) {
			this.orderHistoryId = orderHistoryId;
		}

		public long getEmployeeId() {
			return employeeId;
		}

		public void setEmployeeId(long employeeId) {
			this.employeeId = employeeId;
		}

		public long getOrderId() {
			return orderId;
		}

		public void setOrderId(long orderId) {
			this.orderId = orderId;
		}

		public long getOrderStateId() {
			return orderStateId;
		}

		public void setOrderStateId(long orderStateId) {
			this.orderStateId = orderStateId;
		}

		public String getAddedDate() {
			return addedDate;
		}

		public void setAddedDate(String addedDate) {
			this.addedDate = addedDate;
		}



}
