package in.sweetcherry.pswebservice.models;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;



@Entity
@Table(name="ps_orders")
public class Order {
	
	// ------------------------
		// PRIVATE FIELDS
		// ------------------------
		  
		// An autogenerated id (unique for each user in the db)
		@Id
		@GeneratedValue(strategy = GenerationType.AUTO)
		@Column(name="id_order")
		private long orderId;
		
		@NotNull
		private String reference;
		
		//@NotNull
		@Column(name="id_lang")
		private long langId;
		
		@Column(name="payment")
		private String paymentMode;
		
		@Column(name="total_paid")
		private String totalAmount;
		
		//@NotNull
		@Column(name="current_state")
		private long orderStateId;
		
		@NotNull
		@Column(name="id_customer")
		private long customerId;
		
		//@NotNull
		@Column(name="id_address_delivery")
		private long deliveryAddressId;
		
		@Column(name="id_employee")
		private long employeeId;
		
		@Column(name="date_add")
		@Temporal(TemporalType.TIMESTAMP)
		private Date addedDate;
		
		@NotNull
		@Column(name="delivery_date")
		@Temporal(TemporalType.TIMESTAMP)
		private Date deliveryDate;
		
		@NotNull
		@Column(name="allocated_delivery_slot")
		private long deliverySlotId;
		
		@Column(name="attempted_details")
		private String attemptedDetails;
		
		@Column(name="delivered_details")
		private String deliveredDetails;
		
		@Column(name="handover_details")
		private String handoverDetails;
		
		@Transient
		private Address customerDeliveryAddress;
	
		@Transient
		List<OrderDetail> productList;
		
		@Transient
		private String employeeFirstName;
		
		@Transient
		private String employeeLastName;

		@Transient
		private DeliverySlot deliverySlot;
		
		@Transient
		private String orderStateStr;
		//-----------------------------------
		// PUBLIC METHODS
		//-----------------------------------
		
		public Order() {
			super();
			// TODO Auto-generated constructor stub
		}

		
		public Order(long orderId, String reference, long langId, String paymentMode, String totalAmount, long orderStateId, long customerId,
				long deliveryAddressId, long employeeId, Date addedDate, Date deliveryDate, long deliverySlotId, String attemptedDetails, 
				String deliveredDetails, String handoverDetails) {
			super();
			this.orderId = orderId;
			this.reference = reference;
			this.langId = langId;
			this.paymentMode = paymentMode;
			this.totalAmount = totalAmount;
			this.orderStateId = orderStateId;
			this.customerId = customerId;
			this.deliveryAddressId = deliveryAddressId;
			this.employeeId = employeeId;
			this.addedDate = addedDate;
			this.deliveryDate = deliveryDate;
			this.deliverySlotId = deliverySlotId;
			this.attemptedDetails = attemptedDetails;
			this.deliveredDetails = deliveredDetails;
			this.handoverDetails = handoverDetails;
		}


		public Order(long orderId) {
			super();
			this.orderId = orderId;
		}

		public long getOrderId() {
			return orderId;
		}

		public void setOrderId(long orderId) {
			this.orderId = orderId;
		}

		public String getReference() {
			return reference;
		}

		public void setReference(String reference) {
			this.reference = reference;
		}

		public long getLangId() {
			return langId;
		}

		public void setLangId(long langId) {
			this.langId = langId;
		}

		public String getPaymentMode() {
			return paymentMode;
		}

		public void setPaymentMode(String paymentMode) {
			this.paymentMode = paymentMode;
		}

		public String getTotalAmount() {
			return totalAmount;
		}

		public void setTotalAmount(String totalAmount) {
			this.totalAmount = totalAmount;
		}

		public long getOrderStateId() {
			return orderStateId;
		}

		public void setOrderStateId(long orderStateId) {
			this.orderStateId = orderStateId;
		}

		public long getCustomerId() {
			return customerId;
		}

		public void setCustomerId(long customerId) {
			this.customerId = customerId;
		}

		public long getDeliveryAddressId() {
			return deliveryAddressId;
		}

		public void setDeliveryAddressId(long deliveryAddressId) {
			this.deliveryAddressId = deliveryAddressId;
		}
		
		public long getEmployeeId() {
			return employeeId;
		}

		public void setEmployeeId(long employeeId) {
			this.employeeId = employeeId;
		}

		public Address getCustomerDeliveryAddress() {
			return customerDeliveryAddress;
		}

		public void setCustomerDeliveryAddress(Address customerDeliveryAddress) {
			this.customerDeliveryAddress = customerDeliveryAddress;
		}

		public List<OrderDetail> getProductList() {
			return productList;
		}


		public void setProductList(List<OrderDetail> productList) {
			this.productList = productList;
		}


		public Date getDeliveryDate() {
			return deliveryDate;
		}


		public void setDeliveryDate(Date deliveryDate) {
			this.deliveryDate = deliveryDate;
		}


		public long getDeliverySlotId() {
			return deliverySlotId;
		}


		public void setDeliverySlotId(long deliverySlotId) {
			this.deliverySlotId = deliverySlotId;
		}


		public String getEmployeeFirstName() {
			return employeeFirstName;
		}


		public void setEmployeeFirstName(String employeeFirstName) {
			this.employeeFirstName = employeeFirstName;
		}


		public String getEmployeeLastName() {
			return employeeLastName;
		}


		public void setEmployeeLastName(String employeeLastName) {
			this.employeeLastName = employeeLastName;
		}


		public DeliverySlot getDeliverySlot() {
			return deliverySlot;
		}


		public void setDeliverySlot(DeliverySlot deliverySlot) {
			this.deliverySlot = deliverySlot;
		}


		public String getAttemptedDetails() {
			return attemptedDetails;
		}


		public void setAttemptedDetails(String attemptedDetails) {
			this.attemptedDetails = attemptedDetails;
		}


		public String getDeliveredDetails() {
			return deliveredDetails;
		}


		public void setDeliveredDetails(String deliveredDetails) {
			this.deliveredDetails = deliveredDetails;
		}


		public String getHandoverDetails() {
			return handoverDetails;
		}


		public void setHandoverDetails(String handoverDetails) {
			this.handoverDetails = handoverDetails;
		}

		public String getOrderStateStr() {
			return orderStateStr;
		}

		public void setOrderStateStr(String orderStateStr) {
			this.orderStateStr = orderStateStr;
		}


		public Date getAddedDate() {
			return addedDate;
		}


		public void setAddedDate(Date addedDate) {
			this.addedDate = addedDate;
		}
		
		
}
